# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_shareablefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablefile',
            name='hash',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
