# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_auto_20170617_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablefile',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
