# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_shareablefile_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablefile',
            name='hash',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
