# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_auto_20170618_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablefile',
            name='file',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
